% MAIN_V6_USB_LIVE_APP Start the Hantek 6022BE USB live control panel.

clear; clc;

scriptDir = fileparts(mfilename("fullpath"));
addpath(scriptDir);

fig = hantek_live_app( ...
    "channel", 1, ...
    "sampleRate", 10e6, ...
    "nSamples", 100000, ...
    "voltsPerDiv", 1.0, ...
    "fftMaxHz", 10000, ...
    "timeStartMs", 0, ...
    "timeWindowMs", 5, ...
    "verticalCenter", 0, ...
    "verticalSpan", 5, ...
    "triggerEnabled", true, ...
    "triggerSlope", "rising", ...
    "triggerLevel", NaN, ...
    "triggerPositionPercent", 20, ...
    "refreshPeriod", 0.25, ...
    "applyCalibration", true, ...
    "debugEcho", false);
