% MAIN_V9_USB_DUAL_LIVE_APP Start the dual-channel Hantek 6022BE live panel.

clear; clc;

scriptDir = fileparts(mfilename('fullpath'));
addpath(scriptDir);

fig = hantek_dual_live_app( ...
    'sampleRate', 10e6, ...
    'nSamples', 100000, ...
    'voltsPerDiv', 1.0, ...
    'timeStartMs', 0, ...
    'timeWindowMs', 5, ...
    'fftMaxHz', 10000, ...
    'refreshPeriod', 0.25, ...
    'triggerEnabled', true, ...
    'triggerSource', 'ch1', ...
    'triggerSlope', 'rising', ...
    'triggerLevel', NaN, ...
    'applyCalibration', true, ...
    'debugEcho', false);
