% MAIN_V5_USB_REALTIME Live USB acquisition in MATLAB.
%
% Adjust channel and voltsPerDiv below. Close the figure or press Ctrl+C to stop.

clear; clc;

channel = 1;
voltsPerDiv = 1.0;

state = hantek_realtime_usb( ...
    "channel", channel, ...
    "sampleRate", 1e6, ...
    "nSamples", 20000, ...
    "voltsPerDiv", voltsPerDiv, ...
    "durationSec", inf, ...
    "debugEcho", false);
